name: CD

on:
  push:
    branches:
      - master
      - next
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Installing dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.TRUEWORK_NODE_SDK_NPM_TOKEN }}
        run: npx semantic-release
